### ISSUE TITLE
executeCommand() can crash the application

### ISSUE THREAD

**Issue by Lugn1** [fungover/haze#105]
If you send an empty ping the executeCommand method runs and crashes due to index out of bounds. 

I don't know the best practice to work around this in order to stop the application from crashing. I did try a simple try-catch block (as seen in the screen clipping below) and it prevented it from crashing at least.

![image](https://user-images.githubusercontent.com/112405777/218768035-ca83feb8-cf8f-462b-8789-5cfc81740811.png)

If anyone got a better solution do not hesitate to make suggestions.

**Comment by Ahlberg-iths** [comment]
I'm thinking we could split the input into two variables - one String/Enum that holds the command, and one list/array/string that holds the rest of the information to complete the command (which will be passed as a parameter to the function handling the command in question). If there is a lack of such information, like in your example with a simple `"Ping\r\n"`, that list/array/string would simply be empty. 

I think maybe this could be done already outside of this `executeCommand` function and then be passed in like parameter/parameters instead of the `inputList`. Or adjust that inputList to hold those values, like: string/enum  would be a string at index 0 and the list/array/string would be a string at index 1. 

Sorry for really confusing explanation, but those are my thoughts 😀

**Comment by kappsegla** [comment]
Also if catching an error here we shouldn't really throw a new RunTimeException from the catch block. That will still most probably stop the thread handling the client, and instead an -Error response for invalid command might be the right answer.

Since we are sending a response with client.getOutputStream we can get some sort of IOException telling us something is wrong with the network connection. In that case it's more appropriate to throw an exception higher up in the hierarchy. 
Maybe this method executeCommand should return the response as String or List<String> or byte[] instead of sending the response to the socket directly? That would have some positive things:

We don't need to take the Socket as a parameter.
No IOExceptions to handle in our code. 
We can write Unit tests for the method if it's made public.
