### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kappsegla** [fungover/haze#33]
Sometimes we want to see what our program is doing. For this we can add logging to our application.
Let us set up dependencies for logging with  [Log4j 2](https://logging.apache.org/log4j/2.x/)

Also update the current codebase with log messages for startup and shutdown of server.

For detailed Debug logging of requests and error responses for different commands this should probably be updated individually in separate issues. It needs to be retrofitted to current code and also applied to future implementations.
Add a Discussion with examples and best practices for adding logging to future code implementations. What should be logged?
Errors from invalid commands? Connection/Disconnect from clients. All commands as debug messages?

**Comment by VenuModi** [comment]
Logs should be saved into a "**.txt**" file with necessary information to get a grip on what has happened during the execution / run. 
- Should the file have a size limit on how much information could be saved, if it exceeds should a new file be created where it continues?
- Should we save older logs to a folder with the format <name-date-time>?
- Should all log levels be seen in the file?
- Should log format look like this:  YYYY/MM/DD - HH:MM:SS:MS -  Logger level - Logger message.

Types of logger levels: Info, Debug, Warn, Error, Fatal

https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm

DEBUG | Designates fine-grained informational events that are most useful to debug an application.
INFO | Designates informational messages that highlight the progress of the application at coarse-grained level.
WARN | Designates potentially harmful situations.
ERROR | Designates error events that might still allow the application to continue running.
FATAL | Designates very severe error events that will presumably lead the application to abort.

It could be good if the user can see the log levels on the console window and not only on a .txt file.

These are just a few examples of how we can use INFO, WARN & ERROR

Example of when INFO should be shown:
log.info("starting application")
log.info("closing application")
log.info("created file stored in location C://user/xyz")

Example of when WARN should be shown:
log.warn("Authentication failure")
log.warn("slow performance due to nested function ")
log.warn("Fail to shutdown")

Example of when ERROR should be shown:
log.error("Connection lost")
log.error("Fail to create log file because path does not exist")
log.error("Invalid server port")

**Comment by kappsegla** [comment]
> Logs should be saved into a "**.txt**" file with necessary information to get a grip on what has happened during the execution / run.
> 
> * Should the file have a size limit on how much information could be saved, if it exceeds should a new file be created where it continues?
> * Should we save older logs to a folder with the format ?
> * Should all log levels be seen in the file?
> * Should log format look like this:  YYYY/MM/DD - HH:MM:SS:MS -  Logger level - Logger message.

To start with I wounder if we should have a file as default destination? Or just printing Warnings och errors to the console? Will work great with Docker that way. If someone wants to save logs to files maybe they can update the config file for that later or if you create a config file with both options and having the save to file configuration commented out?
